apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.warningtool.fullname  }}

# 通过spec.selector字段确定这个Service将要使用哪些Label。
# 在本例，这个名warning-service的Service，将会管理所有具有标签app: warningtool的Pod。  
spec:
  type: {{ .Values.service.type }}
  selector:
    app: warningtool
    version: warningtool-1.0.0
  ports:
    - port: 8800
      nodePort: {{ .Values.service.port }}
      targetPort: 8800
      protocol: TCP
      name: http
